[package]
name = "vardict_rs"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "vardict"
path = "src/bin/vardict.rs"

[dependencies]
anyhow = "1.0.100"
bio-types = "1.0.4"
clap = { version = "4.5", features = ["derive"] }
crackle-kit = { git = "https://github.com/Crispy13/crackle-kit", features = [
    "tracing",
] }
regex = "1.12.2"
rust-htslib = { git = "https://github.com/Crispy13/rust-htslib.git", branch = "dev", features = ["libdeflate"] }
smallvec = "1.15.1"
rayon = "1.11.0"

[profile.dev]
incremental = true

[profile.release]
lto = 'thin'
debug = "line-tables-only"

[profile.debug-release]
inherits = "release"
debug = true

[profile.deploy]
inherits = "release"
lto = true
codegen-units = 1
debug = false
